version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: 'tyba_ms'
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8080:8080

  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    env_file:
      - .env.testing
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        ./node_modules/.bin/knex migrate:latest
        ${COMMAND}
      "